### PR TITLE
Local Date parse error fix

### PR DESCRIPTION
**Pull request by jrparikh**

### CODE REVIEW

**Comment by AllisterJWright** [comment]
@jrparikh Can you confirm for me that the change from ISO 8601 (yyyy-MM-ddTHH:mm:ss) to the new format (replacing T with ' ') is congruent with the expected output from the JPA repository?  The data.sql indicates the original format is still expected for inserting to and reading from the h2 database.

**Comment by jrparikh** [comment]
> @jrparikh Can you confirm for me that the change from ISO 8601 (yyyy-MM-ddTHH:mm:ss) to the new format (replacing T with ' ') is congruent with the expected output from the JPA repository? The data.sql indicates the original format is still expected for inserting to and reading from the h2 database.

I actually did not check if the data is consistent with the repository, it was just to make sure that the front-end did not have a 500 error. The database should still have the right data because LocalDateTime from Java actually has the 'T', I just removed it coming in from the front end since the previous iteration was artificially adding the letter when the middle-end parse function was expecting a string of numbers with no actual letters, if that makes any sense.

**Comment by AllisterJWright** [comment]
> > @jrparikh Can you confirm for me that the change from ISO 8601 (yyyy-MM-ddTHH:mm:ss) to the new format (replacing T with ' ') is congruent with the expected output from the JPA repository? The data.sql indicates the original format is still expected for inserting to and reading from the h2 database.
> 
> I actually did not check if the data is consistent with the repository, it was just to make sure that the front-end did not have a 500 error. The database should still have the right data because LocalDateTime from Java actually has the 'T', I just removed it coming in from the front end since the previous iteration was artificially adding the letter when the middle-end parse function was expecting a string of numbers with no actual letters, if that makes any sense.

Okay.  I'll approve the changes for now, but would prefer to have the data.sql file(s) in this and resource-service updated to reflect the format change before merging back into cloud-dev.  Thanks for the quick response

**Review by AllisterJWright — APPROVED** [review]
See comment: update data.sql and add commit to this pull request before merging.

**Pull request merged**
